### ISSUE TITLE
Any Update on Twitter? epiTwitter suddenly stopped working

### ISSUE THREAD

**Issue by emuki** [jmathai/twitter-async#191]
Any Twitter Update?
My application suddenly fails to authenticate on Twitter. 

My settings remain unchanged:

 const EPITWITTER_SIGNATURE_METHOD = 'HMAC-SHA1';
  const EPITWITTER_AUTH_OAUTH = 'oauth';
  const EPITWITTER_AUTH_BASIC = 'basic';
  protected $requestTokenUrl= 'https://api.twitter.com/oauth/request_token';
  protected $accessTokenUrl = 'https://api.twitter.com/oauth/access_token';
  protected $authorizeUrl   = 'https://api.twitter.com/oauth/authorize';
  protected $authenticateUrl= 'https://api.twitter.com/oauth/authenticate';
  protected $apiUrl         = 'http://api.twitter.com';
  protected $apiVersionedUrl= 'http://api.twitter.com';
  protected $searchUrl      = 'http://search.twitter.com';
  protected $userAgent      = 'EpiTwitter (http://github.com/jmathai/twitter-async/tree/)';
  protected $apiVersion     = '1.1';
  protected $isAsynchronous = false;

NB: This used to work but just suddenly stopped
The  echo $e->getMessage() does not even report any error

try  
 {
$twitterObj = new EpiTwitter($consumer_key, $consumer_secret);
                        $twitterObj->setToken($_GET['oauth_token']);  
                          $token = $twitterObj->getAccessToken(array('oauth_verifier' => $_GET['oauth_verifier']));
                          $twitterObj->setToken($token->oauth_token, $token->oauth_token_secret);
                          $twitterInfo = $twitterObj->get_accountVerify_credentials();
                         $twit_user = $twitterInfo->screen_name;
                         $twitter_unique_id=$twitterInfo->id;
                         $description=$twitterInfo->description;
                            $description=addslashes(htmlspecialchars($description));
                         $url=$twitterInfo->url;
}

   catch(EpiTwitterException $e)  
{  
   echo $e->getMessage(); 

}

Any idea what's going on?

**Comment by Yani18** [comment]
hello good day, currently the twitter api to update the function of capture direct messages (DM), please I need your help to know how I can do to update it.
