### ISSUE TITLE
{"errors":[{"message":"Bad Authentication data","code":215}]}'

### ISSUE THREAD

**Issue by frasodel** [jmathai/twitter-async#197]
Hello, 

I'm trying to authenticate a user with my twitter application. I redirected to the twitter page to give permission to the application with my user but when return to my file again and try to verify the credentials gives me the following error: 

Fatal error: Uncaught exception 'EpiTwitterBadRequestException' with message '{"errors":[{"message":"Bad Authentication data","code":215}]}' 

Can anybody help me? Sorry for my english. 

This is my code:

```
    $twIdApp        = 'my_twitter_id_app';
$twAppSecret    = 'my_twitter_app_secret';

    require_once('lib/EpiCurl.php');
require_once('lib/EpiOAuth.php');
require_once('lib/EpiTwitter.php');

$twitterObj = new EpiTwitter($twIdApp, $twAppSecret);

if (!isset($_REQUEST['oauth_token'])) {
    $url = $twitterObj->getAuthorizationUrl();
    header('Location:' . $url);
    exit;
}
else {
    $twitterObj->setToken($_REQUEST['oauth_token']);
    $token              = $twitterObj->getAccessToken();
    $twitterObj->setToken($token->oauth_token, $token->oauth_token_secret);
    $twitterInfo        = $twitterObj->get_accountVerify_credentials();
    echo $twitterInfo->response;
    $username           = $twitterInfo->screen_name;
}
```

In this line is where get the error
$twitterInfo        = $twitterObj->get_accountVerify_credentials();

Thanks!

**Comment by TheBloodLust** [comment]
Step-by-step procedure to the problem is provided in the below link.
[https://github.com/TheBloodLust/Twitter-Spidering](url)

**Comment by jmathai** [comment]
@TheBloodLust I didn't see any code in that repo.

**Comment by TheBloodLust** [comment]
Sorry about that something went wrong!
[TwitterSpidering.docx](https://github.com/jmathai/twitter-async/files/602947/TwitterSpidering.docx)
