### ISSUE TITLE
missing oauth_consumer_key or oauth_token

### ISSUE THREAD

**Issue by boantp** [jmathai/twitter-async#98]
Fatal error: Uncaught exception 'EpiOAuthUnauthorizedException' with message 'OAuth Verification Failed: Can't verify request, missing oauth_consumer_key or oauth_token' in /home/boanstuf/public_html/sign_in_with_promo/EpiOAuth.php:249 
Stack trace: 
#0 /home/boanstuf/public_html/sign_in_with_promo/EpiOAuth.php(228): EpiOAuthException::raise('OAuth Verificat...', 401)
#1 /home/boanstuf/public_html/sign_in_with_promo/EpiOAuth.php(25): EpiOAuthResponse->__get('oauth_token')
#2 /home/boanstuf/public_html/sign_in_with_promo/start.php(9): EpiOAuth->getAuthenticateUrl() #3 {main} thrown in /home/boanstuf/public_html/sign_in_with_promo/EpiOAuth.php on line 249

**Comment by DenisBabarykin** [comment]
Why issue was closed?
